# Generated by Django 5.2.4 on 2025-07-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudreason',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
